name: Test 1

on:
  push:
    branches: [ "master" ]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: display now
        run: date
