name: Test F

on:
  push:
    branches: [ "main" ]

jobs:
  demo2:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cederlys/timestamped-docker
    steps:
      - name: display time
        run: date
      - name: display image build time
        run: cat /etc/buildtime
